/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVendedoresRouteImport } from './routes/_app/vendedores'
import { Route as AppVendasRouteImport } from './routes/_app/vendas'
import { Route as AppUtilizadoresRouteImport } from './routes/_app/utilizadores'
import { Route as AppStockRouteImport } from './routes/_app/stock'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppEmpresaRouteImport } from './routes/_app/empresa'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContaCorrenteRouteImport } from './routes/_app/conta-corrente'
import { Route as AppCatalogoRouteImport } from './routes/_app/catalogo'
import { Route as AppCaixaRouteImport } from './routes/_app/caixa'
import { Route as AppRegistosIndexRouteImport } from './routes/_app/registos.index'
import { Route as AppOficinaIndexRouteImport } from './routes/_app/oficina.index'
import { Route as AppClientesIndexRouteImport } from './routes/_app/clientes.index'
import { Route as AppRegistosIdRouteImport } from './routes/_app/registos.$id'
import { Route as AppOficinaRelatoriosRouteImport } from './routes/_app/oficina.relatorios'
import { Route as AppOficinaNovaRouteImport } from './routes/_app/oficina.nova'
import { Route as AppOficinaAdminRouteImport } from './routes/_app/oficina.admin'
import { Route as AppClientesIdRouteImport } from './routes/_app/clientes.$id'
import { Route as AppOficinaIdIndexRouteImport } from './routes/_app/oficina.$id.index'
import { Route as AppOficinaIdImprimirRouteImport } from './routes/_app/oficina.$id.imprimir'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendedoresRoute = AppVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppUtilizadoresRoute = AppUtilizadoresRouteImport.update({
  id: '/utilizadores',
  path: '/utilizadores',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresaRoute = AppEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContaCorrenteRoute = AppContaCorrenteRouteImport.update({
  id: '/conta-corrente',
  path: '/conta-corrente',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoRoute = AppCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AppRoute,
} as any)
const AppCaixaRoute = AppCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistosIndexRoute = AppRegistosIndexRouteImport.update({
  id: '/registos/',
  path: '/registos/',
  getParentRoute: () => AppRoute,
} as any)
const AppOficinaIndexRoute = AppOficinaIndexRouteImport.update({
  id: '/oficina/',
  path: '/oficina/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistosIdRoute = AppRegistosIdRouteImport.update({
  id: '/registos/$id',
  path: '/registos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOficinaRelatoriosRoute = AppOficinaRelatoriosRouteImport.update({
  id: '/oficina/relatorios',
  path: '/oficina/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppOficinaNovaRoute = AppOficinaNovaRouteImport.update({
  id: '/oficina/nova',
  path: '/oficina/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppOficinaAdminRoute = AppOficinaAdminRouteImport.update({
  id: '/oficina/admin',
  path: '/oficina/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOficinaIdIndexRoute = AppOficinaIdIndexRouteImport.update({
  id: '/oficina/$id/',
  path: '/oficina/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppOficinaIdImprimirRoute = AppOficinaIdImprimirRouteImport.update({
  id: '/oficina/$id/imprimir',
  path: '/oficina/$id/imprimir',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/caixa': typeof AppCaixaRoute
  '/catalogo': typeof AppCatalogoRoute
  '/conta-corrente': typeof AppContaCorrenteRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresa': typeof AppEmpresaRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/stock': typeof AppStockRoute
  '/utilizadores': typeof AppUtilizadoresRoute
  '/vendas': typeof AppVendasRoute
  '/vendedores': typeof AppVendedoresRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/oficina/admin': typeof AppOficinaAdminRoute
  '/oficina/nova': typeof AppOficinaNovaRoute
  '/oficina/relatorios': typeof AppOficinaRelatoriosRoute
  '/registos/$id': typeof AppRegistosIdRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/oficina/': typeof AppOficinaIndexRoute
  '/registos/': typeof AppRegistosIndexRoute
  '/oficina/$id/imprimir': typeof AppOficinaIdImprimirRoute
  '/oficina/$id/': typeof AppOficinaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/caixa': typeof AppCaixaRoute
  '/catalogo': typeof AppCatalogoRoute
  '/conta-corrente': typeof AppContaCorrenteRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresa': typeof AppEmpresaRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/stock': typeof AppStockRoute
  '/utilizadores': typeof AppUtilizadoresRoute
  '/vendas': typeof AppVendasRoute
  '/vendedores': typeof AppVendedoresRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/oficina/admin': typeof AppOficinaAdminRoute
  '/oficina/nova': typeof AppOficinaNovaRoute
  '/oficina/relatorios': typeof AppOficinaRelatoriosRoute
  '/registos/$id': typeof AppRegistosIdRoute
  '/clientes': typeof AppClientesIndexRoute
  '/oficina': typeof AppOficinaIndexRoute
  '/registos': typeof AppRegistosIndexRoute
  '/oficina/$id/imprimir': typeof AppOficinaIdImprimirRoute
  '/oficina/$id': typeof AppOficinaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/caixa': typeof AppCaixaRoute
  '/_app/catalogo': typeof AppCatalogoRoute
  '/_app/conta-corrente': typeof AppContaCorrenteRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/empresa': typeof AppEmpresaRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/stock': typeof AppStockRoute
  '/_app/utilizadores': typeof AppUtilizadoresRoute
  '/_app/vendas': typeof AppVendasRoute
  '/_app/vendedores': typeof AppVendedoresRoute
  '/_app/clientes/$id': typeof AppClientesIdRoute
  '/_app/oficina/admin': typeof AppOficinaAdminRoute
  '/_app/oficina/nova': typeof AppOficinaNovaRoute
  '/_app/oficina/relatorios': typeof AppOficinaRelatoriosRoute
  '/_app/registos/$id': typeof AppRegistosIdRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/oficina/': typeof AppOficinaIndexRoute
  '/_app/registos/': typeof AppRegistosIndexRoute
  '/_app/oficina/$id/imprimir': typeof AppOficinaIdImprimirRoute
  '/_app/oficina/$id/': typeof AppOficinaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/caixa'
    | '/catalogo'
    | '/conta-corrente'
    | '/dashboard'
    | '/empresa'
    | '/relatorios'
    | '/stock'
    | '/utilizadores'
    | '/vendas'
    | '/vendedores'
    | '/clientes/$id'
    | '/oficina/admin'
    | '/oficina/nova'
    | '/oficina/relatorios'
    | '/registos/$id'
    | '/clientes/'
    | '/oficina/'
    | '/registos/'
    | '/oficina/$id/imprimir'
    | '/oficina/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/caixa'
    | '/catalogo'
    | '/conta-corrente'
    | '/dashboard'
    | '/empresa'
    | '/relatorios'
    | '/stock'
    | '/utilizadores'
    | '/vendas'
    | '/vendedores'
    | '/clientes/$id'
    | '/oficina/admin'
    | '/oficina/nova'
    | '/oficina/relatorios'
    | '/registos/$id'
    | '/clientes'
    | '/oficina'
    | '/registos'
    | '/oficina/$id/imprimir'
    | '/oficina/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/caixa'
    | '/_app/catalogo'
    | '/_app/conta-corrente'
    | '/_app/dashboard'
    | '/_app/empresa'
    | '/_app/relatorios'
    | '/_app/stock'
    | '/_app/utilizadores'
    | '/_app/vendas'
    | '/_app/vendedores'
    | '/_app/clientes/$id'
    | '/_app/oficina/admin'
    | '/_app/oficina/nova'
    | '/_app/oficina/relatorios'
    | '/_app/registos/$id'
    | '/_app/clientes/'
    | '/_app/oficina/'
    | '/_app/registos/'
    | '/_app/oficina/$id/imprimir'
    | '/_app/oficina/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vendedores': {
      id: '/_app/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof AppVendedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas': {
      id: '/_app/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/utilizadores': {
      id: '/_app/utilizadores'
      path: '/utilizadores'
      fullPath: '/utilizadores'
      preLoaderRoute: typeof AppUtilizadoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empresa': {
      id: '/_app/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AppEmpresaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conta-corrente': {
      id: '/_app/conta-corrente'
      path: '/conta-corrente'
      fullPath: '/conta-corrente'
      preLoaderRoute: typeof AppContaCorrenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogo': {
      id: '/_app/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AppCatalogoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caixa': {
      id: '/_app/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AppCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/registos/': {
      id: '/_app/registos/'
      path: '/registos'
      fullPath: '/registos/'
      preLoaderRoute: typeof AppRegistosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oficina/': {
      id: '/_app/oficina/'
      path: '/oficina'
      fullPath: '/oficina/'
      preLoaderRoute: typeof AppOficinaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/registos/$id': {
      id: '/_app/registos/$id'
      path: '/registos/$id'
      fullPath: '/registos/$id'
      preLoaderRoute: typeof AppRegistosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oficina/relatorios': {
      id: '/_app/oficina/relatorios'
      path: '/oficina/relatorios'
      fullPath: '/oficina/relatorios'
      preLoaderRoute: typeof AppOficinaRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oficina/nova': {
      id: '/_app/oficina/nova'
      path: '/oficina/nova'
      fullPath: '/oficina/nova'
      preLoaderRoute: typeof AppOficinaNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oficina/admin': {
      id: '/_app/oficina/admin'
      path: '/oficina/admin'
      fullPath: '/oficina/admin'
      preLoaderRoute: typeof AppOficinaAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$id': {
      id: '/_app/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oficina/$id/': {
      id: '/_app/oficina/$id/'
      path: '/oficina/$id'
      fullPath: '/oficina/$id/'
      preLoaderRoute: typeof AppOficinaIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oficina/$id/imprimir': {
      id: '/_app/oficina/$id/imprimir'
      path: '/oficina/$id/imprimir'
      fullPath: '/oficina/$id/imprimir'
      preLoaderRoute: typeof AppOficinaIdImprimirRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCaixaRoute: typeof AppCaixaRoute
  AppCatalogoRoute: typeof AppCatalogoRoute
  AppContaCorrenteRoute: typeof AppContaCorrenteRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmpresaRoute: typeof AppEmpresaRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppStockRoute: typeof AppStockRoute
  AppUtilizadoresRoute: typeof AppUtilizadoresRoute
  AppVendasRoute: typeof AppVendasRoute
  AppVendedoresRoute: typeof AppVendedoresRoute
  AppClientesIdRoute: typeof AppClientesIdRoute
  AppOficinaAdminRoute: typeof AppOficinaAdminRoute
  AppOficinaNovaRoute: typeof AppOficinaNovaRoute
  AppOficinaRelatoriosRoute: typeof AppOficinaRelatoriosRoute
  AppRegistosIdRoute: typeof AppRegistosIdRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppOficinaIndexRoute: typeof AppOficinaIndexRoute
  AppRegistosIndexRoute: typeof AppRegistosIndexRoute
  AppOficinaIdImprimirRoute: typeof AppOficinaIdImprimirRoute
  AppOficinaIdIndexRoute: typeof AppOficinaIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCaixaRoute: AppCaixaRoute,
  AppCatalogoRoute: AppCatalogoRoute,
  AppContaCorrenteRoute: AppContaCorrenteRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmpresaRoute: AppEmpresaRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppStockRoute: AppStockRoute,
  AppUtilizadoresRoute: AppUtilizadoresRoute,
  AppVendasRoute: AppVendasRoute,
  AppVendedoresRoute: AppVendedoresRoute,
  AppClientesIdRoute: AppClientesIdRoute,
  AppOficinaAdminRoute: AppOficinaAdminRoute,
  AppOficinaNovaRoute: AppOficinaNovaRoute,
  AppOficinaRelatoriosRoute: AppOficinaRelatoriosRoute,
  AppRegistosIdRoute: AppRegistosIdRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppOficinaIndexRoute: AppOficinaIndexRoute,
  AppRegistosIndexRoute: AppRegistosIndexRoute,
  AppOficinaIdImprimirRoute: AppOficinaIdImprimirRoute,
  AppOficinaIdIndexRoute: AppOficinaIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
