/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVendedoresRouteImport } from './routes/_app/vendedores'
import { Route as AppUtilizadoresRouteImport } from './routes/_app/utilizadores'
import { Route as AppEmpresaRouteImport } from './routes/_app/empresa'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppCatalogoRouteImport } from './routes/_app/catalogo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendedoresRoute = AppVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AppRoute,
} as any)
const AppUtilizadoresRoute = AppUtilizadoresRouteImport.update({
  id: '/utilizadores',
  path: '/utilizadores',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresaRoute = AppEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoRoute = AppCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/catalogo': typeof AppCatalogoRoute
  '/clientes': typeof AppClientesRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresa': typeof AppEmpresaRoute
  '/utilizadores': typeof AppUtilizadoresRoute
  '/vendedores': typeof AppVendedoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/catalogo': typeof AppCatalogoRoute
  '/clientes': typeof AppClientesRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresa': typeof AppEmpresaRoute
  '/utilizadores': typeof AppUtilizadoresRoute
  '/vendedores': typeof AppVendedoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/catalogo': typeof AppCatalogoRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/empresa': typeof AppEmpresaRoute
  '/_app/utilizadores': typeof AppUtilizadoresRoute
  '/_app/vendedores': typeof AppVendedoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/catalogo'
    | '/clientes'
    | '/dashboard'
    | '/empresa'
    | '/utilizadores'
    | '/vendedores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/catalogo'
    | '/clientes'
    | '/dashboard'
    | '/empresa'
    | '/utilizadores'
    | '/vendedores'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/catalogo'
    | '/_app/clientes'
    | '/_app/dashboard'
    | '/_app/empresa'
    | '/_app/utilizadores'
    | '/_app/vendedores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vendedores': {
      id: '/_app/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof AppVendedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/utilizadores': {
      id: '/_app/utilizadores'
      path: '/utilizadores'
      fullPath: '/utilizadores'
      preLoaderRoute: typeof AppUtilizadoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empresa': {
      id: '/_app/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AppEmpresaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogo': {
      id: '/_app/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AppCatalogoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCatalogoRoute: typeof AppCatalogoRoute
  AppClientesRoute: typeof AppClientesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmpresaRoute: typeof AppEmpresaRoute
  AppUtilizadoresRoute: typeof AppUtilizadoresRoute
  AppVendedoresRoute: typeof AppVendedoresRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCatalogoRoute: AppCatalogoRoute,
  AppClientesRoute: AppClientesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmpresaRoute: AppEmpresaRoute,
  AppUtilizadoresRoute: AppUtilizadoresRoute,
  AppVendedoresRoute: AppVendedoresRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
